sudo: false

language: go

go:
  - 1.5.3

before_install:
  - go get github.com/modocache/gover
  - pip install --user codecov

script:
  # Run the unit tests suite
  - go test -v ./...
  # Collect coverage reports
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -i sh -c {}
  # Merge coverage reports
  - gover . coverprofile.txt
after_success:
  - codecov --file coverprofile.txt